Core\AdminBundle\Entity\Campus:
    type: entity
    table: Campus
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 25
            fixed: false
            nullable: false
        usuario:
            type: string
            length: 25
            fixed: false
            nullable: false
        clave:
            type: string
            length: 55
            fixed: false
            nullable: false
        nom:
            type: string
            length: 5
            fixed: false
            nullable: false
        activo:
            type: integer
            unsigned: false
            nullable: false
    lifecycleCallbacks: {  }
