Core\AdminBundle\Entity\Ssidmacauth:
    type: entity
    table: ssidmacauth
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: ID
            generator:
                strategy: IDENTITY
        username:
            type: string
            length: 20
            fixed: false
            nullable: false
        macaddress:
            type: string
            length: 20
            fixed: false
            nullable: false
        ssid:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
