##### ADMINISTRATOR :: LOGIN #####

admin:
    pattern:  /admin/
    defaults: { _controller: CoreAdminBundle:Admin:admin }

admin_login:
    pattern:  /admin/login/
    defaults: { _controller: CoreAdminBundle:Admin:login }

admin_logout:
    pattern:  /admin/logout/
    defaults: { _controller: CoreAdminBundle:Admin:logout }

admin_home:
    pattern:  /admin/{session}/
    defaults: { _controller: CoreAdminBundle:Admin:home }

##### ADMINISTRATOR :: USUARIOS #####

admin_usuarios_crear:
    pattern:  /admin/users/new/{session}/
    defaults: { _controller: CoreAdminBundle:Users:new }

admin_usuarios_modificar:
    pattern:  /admin/users/edit/{session}/{id}/
    defaults: { _controller: CoreAdminBundle:Users:edit }

admin_usuarios_eliminar_macs:
    pattern:  /admin/users/delmac/{session}/{id}/{campus}/
    defaults: { _controller: CoreAdminBundle:Users:delmac }

admin_usuarios_eliminar:
    pattern:  /admin/users/del/{session}/{id}/{campus}/
    defaults: { _controller: CoreAdminBundle:Users:del }

admin_usuarios_limpiar:
    pattern:  /admin/users/clear/{session}/{id}/{campus}/
    defaults: { _controller: CoreAdminBundle:Users:clear }

admin_reset_macs:
    pattern:  /admin/users/resetmacs/
    defaults: { _controller: CoreAdminBundle:Users:resetmacs }

##### ADMINISTRATOR :: REPORTES #####

admin_reportes:
    pattern:  /admin/reports/list/{session}/{type}/
    defaults: { _controller: CoreAdminBundle:Reports:index }

admin_reportes_listar_reg:
    pattern:  /admin/reports/listreg/{session}/{campus}/
    defaults: { _controller: CoreAdminBundle:Reports:listreg }

admin_reportes_listar_unreg:
    pattern:  /admin/reports/listunreg/{session}/{campus}/
    defaults: { _controller: CoreAdminBundle:Reports:listunreg }

admin_reportes_activos:
    pattern:  /admin/reports/active/{session}/{campus}/{i}/{f}/
    defaults: { _controller: CoreAdminBundle:Reports:active }

admin_reportes_historial:
    pattern:  /admin/reports/history/{session}/{campus}/{i}/{f}/
    defaults: { _controller: CoreAdminBundle:Reports:history }

admin_reportes_mantenimiento:
    pattern:  /admin/reports/maintenance/{session}/{campus}/
    defaults: { _controller: CoreAdminBundle:Reports:maintenance }

##### PORTAL :: LOGIN #####

start:
    pattern:  /
    defaults: { _controller: CoreAdminBundle:Login:start }

portal:
    pattern:  /login/
    defaults: { _controller: CoreAdminBundle:Login:login }

portal_error:
    pattern:  /login/error/
    defaults: { _controller: CoreAdminBundle:Login:error }

portal_alums:
    pattern:  /login/estudiantes/
    defaults: { _controller: CoreAdminBundle:Login:login }

portal_profesors:
    pattern:  /login/docentes/
    defaults: { _controller: CoreAdminBundle:Login:login }

portal_register:
    pattern:  /register/
    defaults: { _controller: CoreAdminBundle:Login:register }

portal_reset_pass:
    pattern:  /resetpass/
    defaults: { _controller: CoreAdminBundle:Login:reset }

portal_change_pass:
    pattern:  /changepass/
    defaults: { _controller: CoreAdminBundle:Login:change }

portal_welcome:
    pattern:  /bienvenida.{_format}/
    defaults: { _controller: CoreAdminBundle:Login:welcome, _format: html }
    requirements:
      _format:  html